### ISSUE TITLE
Does not decode ed25519 key types

### ISSUE THREAD

**Issue by knightian** [ConradIrwin/gpg-decoder#3]
Example item to decode:

-----BEGIN PGP SIGNATURE-----

iHUEARYIAB0WIQTQxgkc8xoQdEENoazOo9yFyPilawUCYWgWcAAKCRDOo9yFyPil
a9RjAP9Gaquy9X77EX0XtYQQS7ZDXM8jLbM0QovN9v+cjREZkwEA4QNFLh+fkPHS
9JK2F3RVM6s/Mq5cpqBYbIcbFk9Ibws=
=2DTF
-----END PGP SIGNATURE-----

It decodes publicKeyAlgorithm as "undefined" however it should be ed25519

**Comment by ConradIrwin** [comment]
Thanks! Likely it's just missing some definitions here: https://github.com/ConradIrwin/gpg-decoder/blob/master/decode.js#L26.

Would you be able to add the missing ones?

**Comment by techfoxactual** [comment]
@ConradIrwin yea I just sent you a pull request now, 0x16 is decimal 22 so that should do it

**Comment by ConradIrwin** [comment]
Thanks! Merged. 

It looks like it still can't decode subpacket type 0x21 (33) in the example you shared, but that can be solved separately I'm sure.

**Comment by techfoxactual** [comment]
Yea I couldn’t work out what it was looking at the PGP spec, even had to go digging just to make sure that 22 was ed25519, still too new for the spec and doco to catch up I guess!
